#! /bin/bash

# make java applications behave nice within dwm
AWT_TOOLKIT=MToolkit
export AWT_TOOLKIT
wmname LG3D
# Detect multiple displays
xrandr --auto

# statusbar loop
while true; do
    xsetroot -name "$(rstatus)"
    sleep 1m # update every minute
done &

# start dwm in a loop to enable restarts
while true; do
    # Log std error to a file
    # set wallpaper
    feh --bg-fill /home/markus/Pictures/2560x1440-light-blue-solid-color-background.jpg
    dwm 2> ~/.dwm.log
done

